# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('week', models.TextField(max_length=10)),
                ('url', models.TextField(max_length=1000)),
            ],
        ),
    ]
